### ISSUE TITLE
crocodile chew : problem with `git rev-list`

### ISSUE THREAD

**Issue by yanicklandry** [ladjs/lad#252] opened 2017-07-12 03:50 UTC
* **Version**: v8.1.3
* **Platform**: Darwin Yanicks-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun 25 17:14:55 PDT 2017; root:xnu-3789.70.16~9/RELEASE_X86_64 x86_64
* **Subsystem**: ?

During the process of a `crocodile chew`, there is a `git rev-list` command that is executed and fails :

```
✗ An error occured while cloning the repository from GitHub, please try again or file an issue with the below output:

Error: Command failed: git describe --tags `git rev-list --tags --max-count=1`
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=<n>
    --max-age=<epoch>
    --min-age=<epoch>
    --sparse
    --no-merges
    --min-parents=<n>
    --no-min-parents
    --max-parents=<n>
    --no-max-parents
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=<n> | --no-abbrev
    --abbrev-commit
    --left-right
    --count
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
fatal: No names found, cannot describe anything.
 `git describe --tags `git rev-list --tags --max-count=1`` (exited with error code 128)
    at callback (/usr/local/lib/node_modules/crocodile/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:277:5)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
```

**Comment by niftylettuce** [comment] 2017-07-12 04:58
hi @yanicklandry nice to see you here - this is a duplicate of #251 - but I am going to release a new stable version of this framework very soon - please join us in Slack so you will be notified! http://slack.crocodilejs.com

**Closed** 2017-09-04 04:35 UTC
